FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt /requirements.txt

RUN apt-get update && apt-get install -y curl
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

COPY . .

EXPOSE 8800
